# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

skip_files:
 - ^node_modules$

handlers:
- url: /favicon\.ico
  static_files: public/static/images/favicon.ico
  upload: public/static/images/favicon\.ico

env_variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: 88passord
  MYSQL_DATABASE: emailshelf
  INSTANCE_CONNECTION_NAME: zeipt-node1:europe-west1:zeipt-node-db

beta_settings:
  cloud_sql_instances: zeipt-node1:europe-west1:zeipt-node-db